# NOT used with gcloud: application, version
# application: google.com:cloud-next-library
# version: one

runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /admin/.*
  script: admin.application
  login: admin
  secure: always

- url: /_ah/push-handlers/.*
  script: admin.application
  login: admin

- url: .*
  script: main.application
  login: required

builtins:
- deferred: on
# - appstats: on

libraries:
- name: jinja2
  version: "2.6"

inbound_services:
- warmup
